version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    allow:
      - dependency-name: '@neuronection/assistant-ui'
    commit-message:
      prefix: deps
    labels:
      - dependencies
