export type {
  AiContextPreview,
  AiToolArgument,
  AiToolInfo,
  EditorTransformJobOut,
  EditorTransformJobState,
  EditorTransformJobStatus,
  EditorTransformMode,
  EditorTransformRequest,
  GenerateContext,
  GenerateScope,
  McpInfo,
  McpToolInfo,
  TranscriptionResult,
} from './ai'

export {
  cancelEditorTransformJob,
  contextVars,
  getEditorTransformJob,
  listAiTools,
  listMcpInfo,
  previewAiContext,
  startEditorTransform,
  transcribeAudio,
} from './ai'

export type {
  CostsSummary,
  DailyEntry,
  Diagnostics,
  ErrorTagProfile,
  ExamStatusEntry,
  MatrixCell,
  Overview,
  Recommendation,
  SpeedAccuracyEntry,
  TaskCost,
} from './analytics'

export {
  getCosts,
  getDiagnostics,
  getExamStatus,
  getOverview,
  getRecommendations,
  setDailyGoal,
} from './analytics'

export type {
  ChatAttachmentInput,
  ChatAttachmentKind,
  ChatBranchNode,
  ChatBranchTree,
  ChatCitation,
  ChatContextData,
  ChatMessage,
  ChatProposal,
  ChatRead,
  ChatSession,
  ChatToolCall,
  ChatTrace,
  ChatTraceRound,
  MentionKind,
  MentionRef,
} from './chat'

export {
  approveChatProposal,
  askAboutExerciseSession,
  askAboutQuestion,
  createChatSession,
  deleteChatSession,
  dismissChatProposal,
  editChatMessage,
  getChatBranchTree,
  getChatContext,
  listChatMessages,
  listChatSessions,
  patchChatMessageState,
  regenerateChatMessage,
  renameChatSession,
  selectChatVariant,
  sendChatMessage,
  stopChatTurn,
  updateChatSessionEmbeddings,
} from './chat'

export {
  ApiError,
  apiDetailMessage,
  apiFetch,
  blobUrl,
  getActiveProfile,
  setActiveProfile,
  unsupportedTypeDetail,
} from './client'

export type {
  AllocationInfo,
  ConceptDraft,
  ConceptDraftEntry,
  ConceptGraph,
  ConceptLinkDraft,
  ConceptNode,
  ConceptNodeDraft,
  Course,
  CourseBundlePreview,
  CourseDefaultTaskInfo,
  CourseTaskInfo,
  CourseTypeInfo,
  NodeArtifacts,
  NodeCounts,
  NodeDetail,
  NodeFolderLink,
  NodeInfo,
  NodeReview,
  NodeWorkspace,
  OrganizerFinding,
  OutlineDraft,
  OutlineDraftChapter,
  OutlineDraftSection,
  ScopeCounts,
  WorkspaceChild,
  WorkspaceFolder,
  WorkspaceMaterial,
  WorkspaceNote,
} from './courses'

export {
  addNode,
  addNodeConcept,
  assignCourseTask,
  assignCourseTaskDefault,
  commitConcepts,
  conceptGraph,
  courseExportUrl,
  courseTree,
  createCourse,
  createCourseType,
  deleteCourse,
  deleteNode,
  draftNodeNote,
  extractConcepts,
  getNode,
  getNodeArtifacts,
  importCourseBundle,
  listCourseTaskDefaults,
  listCourseTasks,
  listCourseTypes,
  listCourses,
  listStudyStates,
  moveNode,
  nodeWorkspace,
  outlineCommit,
  outlineDraft,
  removeNodeConcept,
  renameNode,
  restoreNode,
  reviewNode,
  setStudyState,
  updateCourse,
  updateNode,
} from './courses'

export type {
  DrillPattern,
  ExerciseInfo,
  ExerciseSessionInfo,
  ExerciseStepInfo,
  ExerciseStepInput,
  HintResult,
  PatternProposal,
  StepCheck,
} from './exercises'

export {
  createExercise,
  createPattern,
  deleteExercise,
  drillPatterns,
  exerciseSteps,
  generateExercise,
  getExercise,
  listExercises,
  moveExercise,
  proposePatterns,
  renameExercise,
  requestHint,
  similarExercise,
  startDrill,
  startExerciseSession,
  submitStepAnswer,
} from './exercises'

export type {
  FlashcardInfo,
  ReviewResult,
} from './flashcards'

export {
  ankiExportUrl,
  dueFlashcards,
  generateFlashcards,
  importAnkiDeck,
  listFlashcards,
  reviewFlashcard,
} from './flashcards'

export type {
  Folder,
  FolderDeleteInfo,
  FolderDeleteInfoNodeLink,
} from './folders'

export {
  createFolder,
  deleteFolder,
  getFolderDeleteInfo,
  listFolders,
  moveFolder,
  renameFolder,
  unlinkFolder,
} from './folders'

export type {
  JobInfo,
  JobTypeInfo,
  JobsSummary,
} from './jobs'

export {
  deleteFailedJobs,
  deleteJob,
  getJobsSummary,
  listJobTypes,
  listJobs,
  retryFailedJobs,
  retryJob,
} from './jobs'

export type {
  AcceptedTypes,
  BlockDto,
  ComposeKind,
  ComposedMaterial,
  CourseMaterialLink,
  Extraction,
  ExtractionVersionInfo,
  IndexCard,
  Material,
  MaterialDetail,
  MaterialLinkInfo,
  MindmapEditResult,
  PendingDrawing,
  SearchHitDto,
  TextFileEditState,
  UploadResult,
  WorkspaceConcept,
} from './materials'

export {
  COMPOSE_KINDS,
  addMaterialDrawing,
  getAcceptedTypes,
  allocateMaterial,
  allocateNodeFolder,
  assignCourseMaterial,
  composeMaterial,
  copyMaterial,
  createTextFile,
  createTextMaterial,
  deallocateMaterial,
  deallocateNodeFolder,
  deleteMaterial,
  deleteMaterialDrawing,
  deriveMaterial,
  editExtraction,
  getExtractionVersion,
  getMaterial,
  getMaterialLinks,
  listCourseMaterials,
  listExtractionVersions,
  listMaterials,
  mindmapEdit,
  moveMaterial,
  reingestMaterial,
  remapDrawingRefsInMarkdown,
  renameMaterial,
  reocrMaterialDrawing,
  search,
  unassignCourseMaterial,
  updateMaterialDrawing,
  updateTextMaterial,
  uploadMaterial,
} from './materials'

export type {
  NoteActionResult,
  NoteDetailInfo,
  NoteDrawingInfo,
  NoteInfo,
  NoteTagSummary,
  NoteVersionDetailInfo,
  NoteVersionInfo,
  NotesPage,
} from './notes'

export {
  addDrawing,
  composeNote,
  createNote,
  deleteDrawing,
  deleteNote,
  getNote,
  getNoteVersion,
  listNoteTags,
  listNoteVersions,
  listNotes,
  moveNote,
  reocrDrawing,
  restoreNoteVersion,
  runNoteAction,
  saveSessionSummaryNote,
  updateDrawing,
  updateNote,
} from './notes'

export type {
  ImportResult,
  ImportValidation,
  MistakeRow,
  QuizActivity,
  QuizAttempt,
  QuizAttemptRow,
  QuizFeedback,
  QuizQuestion,
  RecognitionResult,
} from './quiz'

export {
  deleteQuiz,
  finishQuizAttempt,
  generateQuiz,
  getQuiz,
  importQpkg,
  importQuiz,
  listMistakes,
  listQuizAttempts,
  listQuizzes,
  moveQuiz,
  qpkgExportUrl,
  quizExportUrl,
  quizQuestions,
  recognizeHandwriting,
  renameQuiz,
  requestQuizHint,
  startQuizAttempt,
  submitQuizAnswer,
} from './quiz'

export type {
  AiModel,
  BackupEntryInfo,
  BackupRecoveryInfo,
  BackupSettingsInfo,
  BackupStatus,
  DefaultTaskInfo,
  Provider,
  ProviderPreset,
  RemoteModelInfo,
  SkillInfo,
  SkillVersionInfo,
  TaskInfo,
} from './settings'

export {
  activateSkillVersion,
  assignTask,
  assignTaskDefault,
  backupExportUrl,
  createBackupNow,
  createModel,
  createProvider,
  deleteBackup,
  deleteModel,
  deleteProvider,
  discoverModels,
  getBackupStatus,
  listModels,
  listPresets,
  listProviders,
  listRemoteModels,
  listSkills,
  listTaskDefaults,
  listTasks,
  restoreBackup,
  restoreBackupByName,
  restoreSkillDefault,
  saveSkillVersion,
  setTaskBudget,
  skillResolution,
  skillTestRun,
  skillVersions,
  testProvider,
  updateBackupSettings,
  updateModel,
  updateProvider,
} from './settings'

export type {
  BrowseEntry,
  BrowseMaterial,
  BrowsePending,
  BrowseResult,
  InboxEntryInfo,
  LinkedSource,
  ScanResult,
} from './sources'

export {
  addSource,
  browseSource,
  deleteSource,
  importInboxFile,
  inboxPath,
  ingestSourceFile,
  listSources,
  relinkSource,
  revealSource,
  scanInbox,
  scanSource,
} from './sources'

export type {
  DeletedItemInfo,
  DesktopFileEntry,
  DesktopFolderListing,
  FsDirEntry,
  FsDirs,
  Health,
  OnboardingState,
  ProfileInfo,
  ProfilePreferences,
  WorkingDirInfo,
  WorkingDirValidation,
} from './system'

export {
  createProfile,
  createSampleCourse,
  deleteProfile,
  desktopFileUrl,
  getHealth,
  getOnboardingState,
  getProfilePreferences,
  getWorkingDir,
  listDeletedItems,
  listDesktopFolder,
  listFsDirs,
  listProfiles,
  purgeDeletedItem,
  registerDesktopDrops,
  resetWorkingDir,
  restoreDeletedItem,
  setWorkingDir,
  updateProfilePreferences,
  validateWorkingDir,
} from './system'
