/**
 * Neuronection family UI capture — Markdown gallery generator (template).
 *
 * Reads the scene catalog (scenes.mjs, repo-owned) and the PNG files present
 * in the output dir, then emits TWO separate tour documents:
 *
 *   - docs/SCREENSHOTS.md        — desktop tour (primary, linked from README)
 *   - docs/SCREENSHOTS.MOBILE.md — mobile tour, written only when at least
 *                                  one *-mobile.png exists on disk
 *
 * Titles, intro copy and the regeneration hint come from
 * `ui-capture.config.json` (`gallery.title`, `gallery.intro`,
 * `gallery.regenCommand`). Invoked by capture.mjs after every run; also
 * runnable via `node capture.mjs --gallery-only`.
 *
 * Additionally writes `<outDir>/tour.manifest.json` — the machine-readable
 * inventory of the tour (ordered scenes, captions, narrations, viewports,
 * GIF path). Consumed by the website tour sync (sync-tours.mjs) and the
 * future AI-video storyboard. Deliberately deterministic: no timestamps,
 * stable key order — regenerating without new captures must be a no-op diff.
 */
import { writeFile, unlink } from "node:fs/promises";
import { existsSync } from "node:fs";
import { relative } from "node:path";

const GENERATED_BANNER = [
  "<!--",
  "  AUTO-GENERATED by scripts/ui-capture/gallery.mjs (family template).",
  "  Do not edit by hand — re-run the capture script to regenerate.",
  "  To add a page, add a scene in scripts/ui-capture/scenes.mjs.",
  "-->",
].join("\n");

// Gallery lives in docs/, images in docs/images/ → relative "images/<file>"
function relImagePath(file) {
  return `images/${file}`;
}

// Derive the mobile doc path from the primary gallery path. Keeps the CLI
// surface minimal: one --gallery flag, the mobile doc is auto-derived.
function mobileGalleryPath(gallery) {
  return gallery.replace(/\.md$/i, ".mobile.md");
}

function sceneBlock(scene, viewport, outDir, regenCommand) {
  const file = `${scene.name}-${viewport}.png`;
  const has = scene.viewports.includes(viewport) && existsSync(`${outDir}/${file}`);

  const lines = [];
  lines.push(`### ${scene.name}`);
  lines.push("");
  lines.push(`_${scene.caption}_`);
  lines.push("");
  if (has) {
    lines.push(`![${scene.name} ${viewport}](${relImagePath(file)})`);
  } else {
    lines.push(
      `> ⚠️ No ${viewport} screenshot yet for **${scene.name}**. Run \`${regenCommand} -- --scene ${scene.name} --viewport ${viewport}\`.`,
    );
  }
  lines.push("");
  return lines.join("\n");
}

function buildFrontMatter(cfg, viewport, siblingDoc, hasSibling) {
  const galleryCfg = cfg.gallery ?? {};
  const projectName = cfg.project?.name ?? "this project";
  const intro =
    galleryCfg.intro ??
    cfg.project?.intro ??
    `Welcome to the visual tour of ${projectName}. These reproducible screenshots showcase the main pages and use cases of the application.`;
  const regenCommand = galleryCfg.regenCommand ?? "./scripts/ui-capture/capture_ui.sh";

  const md = [];
  md.push(GENERATED_BANNER);
  md.push("");
  md.push(`# ${viewport === "desktop" ? galleryCfg.title ?? `${projectName} — Visual Tour` : galleryCfg.mobileTitle ?? `${projectName} — Visual Tour (Mobile)`}`);
  md.push("");
  md.push(intro);
  md.push("");
  if (viewport === "desktop") {
    if (hasSibling) {
      md.push(`> Mobile views: [${siblingDoc}](${siblingDoc})`);
    } else {
      md.push(`> Mobile views: not captured this run — pass \`--viewport mobile\` to \`${regenCommand}\` to generate.`);
    }
  } else {
    md.push("> Mobile-only companion to the desktop tour. See the primary tour document.");
  }
  md.push("");
  return md;
}

/**
 * Generate (or remove, when no PNGs are on disk) the per-viewport gallery doc.
 * Returns the path written, or null if the doc was removed because no PNGs exist.
 */
async function writeViewportGallery(cfg, scenes, groups, { out, galleryPath, viewport, siblingDoc, hasSibling }) {
  const regenCommand = cfg.gallery?.regenCommand ?? "./scripts/ui-capture/capture_ui.sh";
  const anyPresent = scenes.some(
    (s) => s.viewports.includes(viewport) && existsSync(`${out}/${s.name}-${viewport}.png`),
  );

  if (!anyPresent) {
    // No captures for this viewport → drop a stale doc so docs/ stays in
    // sync with what's actually on disk.
    if (existsSync(galleryPath)) {
      await unlink(galleryPath).catch(() => {});
      console.log(`No ${viewport} PNGs found — removed stale ${galleryPath}`);
    }
    return null;
  }

  const md = [...buildFrontMatter(cfg, viewport, siblingDoc, hasSibling)];
  const groupList = groups ?? [...new Set(scenes.map((s) => s.group))];
  for (const group of groupList) {
    const inGroup = scenes.filter((s) => s.group === group);
    if (inGroup.length === 0) continue;
    md.push(`## ${group}`);
    md.push("");
    for (const s of inGroup) md.push(sceneBlock(s, viewport, out, regenCommand));
  }

  await writeFile(galleryPath, md.join("\n"), "utf8");
  return galleryPath;
}

/**
 * Machine-readable tour inventory next to the PNGs. Only scenes with at
 * least one PNG on disk are listed — the manifest describes what exists,
 * never what is planned.
 */
function buildManifest(scenes, cfg, { out, gallery, mobileGallery, writtenDesktop, writtenMobile, root, templateVersion }) {
  const relFromRoot = (absPath) => relative(root, absPath).replaceAll("\\", "/");
  // Story order: the GIF's scene order first (that is the tour narrative),
  // then any remaining scenes in catalog order — consumers like the website
  // grid show the head of the list, so the tour's headline frames lead.
  const order = cfg.gif?.order ?? [];
  const rank = (name) => {
    const i = order.indexOf(name);
    return i === -1 ? order.length : i;
  };
  const ordered = [...scenes].sort((a, b) => rank(a.name) - rank(b.name));
  const manifestScenes = [];
  for (const scene of ordered) {
    const files = {};
    for (const vp of scene.viewports) {
      if (existsSync(`${out}/${scene.name}-${vp}.png`)) files[vp] = `${scene.name}-${vp}.png`;
    }
    if (Object.keys(files).length === 0) continue;
    manifestScenes.push({
      name: scene.name,
      group: scene.group ?? null,
      caption: scene.caption ?? null,
      ...(scene.narration ? { narration: scene.narration } : {}),
      viewports: Object.keys(files),
      files,
    });
  }
  return {
    version: 1,
    templateVersion: templateVersion ?? null,
    project: cfg.project?.name ?? null,
    generatedBy: "scripts/ui-capture (Neuronection family template)",
    gallery: {
      desktop: writtenDesktop ? relFromRoot(gallery) : null,
      mobile: writtenMobile ? relFromRoot(mobileGallery) : null,
    },
    gif: cfg.gif?.output ?? null,
    scenes: manifestScenes,
  };
}

export async function generateGallery(scenes, groups, opts) {
  const { cfg, out, gallery } = opts;
  const mobileGallery = mobileGalleryPath(gallery);
  const siblingName = mobileGallery.split("/").pop();

  // Desktop is the primary doc; the mobile companion is generated only if its
  // PNGs are on disk. Mobile state is resolved first so the desktop doc's
  // "mobile views" footer line is accurate.
  const mobilePresent = scenes.some(
    (s) => s.viewports.includes("mobile") && existsSync(`${out}/${s.name}-mobile.png`),
  );

  const writtenDesktop = await writeViewportGallery(cfg, scenes, groups, {
    out,
    galleryPath: gallery,
    viewport: "desktop",
    siblingDoc: siblingName,
    hasSibling: mobilePresent,
  });
  const writtenMobile = mobilePresent
    ? await writeViewportGallery(cfg, scenes, groups, {
        out,
        galleryPath: mobileGallery,
        viewport: "mobile",
        siblingDoc: gallery.split("/").pop(),
        hasSibling: writtenDesktop !== null,
      })
    : await (async () => {
        // No mobile PNGs — drop a stale mobile doc so docs/ stays in sync
        // with what's actually on disk (e.g. after a --viewport desktop run).
        if (existsSync(mobileGallery)) {
          await unlink(mobileGallery).catch(() => {});
          console.log(`No mobile PNGs found — removed stale ${mobileGallery}`);
        }
        return null;
      })();

  const manifest = buildManifest(scenes, cfg, {
    out,
    gallery,
    mobileGallery,
    writtenDesktop,
    writtenMobile,
    root: opts.root,
    templateVersion: opts.templateVersion,
  });
  const manifestPath = opts.manifest ?? `${out}/tour.manifest.json`;
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
  console.log(`Manifest: ${manifestPath}`);

  return { desktop: writtenDesktop, mobile: writtenMobile, manifest: manifestPath };
}
